My first pull request
Sonickmumba/Hello-world pull request #3
Opened 2022-06-28 21:33 UTC by Sonickmumba

2022-06-28 22:03 UTC, codecaiine requested changes

2022-06-28 22:03 UTC, codecaiine commented on README.md
> -### Deployment
- [ ] You README file is descriptive, you did well, but please add another session for getting started to show how use your project.

2022-06-28 22:10 UTC, codecaiine commented
Hi @Sonickmumba , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
:heavy_check_mark:  Good commit history
:heavy_check_mark: Descriptive commits
:heavy_check_mark: Good project implementation

## Required Changes ♻️

- [ ]  Please a summary describing introduced changes in your pull request with more details.
- [ ] Please Fix your Linters errors cause the result should be green. 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-29 12:54 UTC, Sonickmumba commented
Dear @codecaiine,
I have managed to fix the linter errors and added the session for getting started on the README.md file. Kindly check it out.

Thanks and regards.

2022-06-30 16:42 UTC, sumairq approved these changes
### Hi @Sonickmumba     , 

<img src="https://media2.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔️ Good commit history
✔️Linters are passing
✔️Very professional README
✔️Correct Github flow
✔️Descriptive PR

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-30 17:55 UTC, merged